### ISSUE TITLE
Blackbox process crashes if too many files match the configured regex

### ISSUE THREAD

**Issue by carlo-colombo** [cloudfoundry/blackbox#11] opened 2018-12-03 11:22 UTC
We had a bosh deployment failing due to the blackbox process crashing with error

```
2018/11/14 19:13:27 Seeked /var/vcap/sys/log/kube-apiserver/audit-2018-11-09T19-23-44.754.log - &{Offset:0 Whence:2}
2018/11/14 19:13:27 lines flushed; exiting tailer
2018/11/14 19:13:27 FATAL -- failed to create Watcher
goroutine 4089 [running]:
runtime/debug.Stack(0xc420012ba0, 0x21, 0x0)
        /var/vcap/data/packages/golang/d2abe6ed3ac3b89eb235e73ed653ec3a635e3d9f/src/runtime/debug/stack.go:24 +0xa7
github.com/hpcloud/tail/util.Fatal(0x6498cf, 0x18, 0x0, 0x0, 0x0)
        /var/vcap/packages/blackbox/src/github.com/hpcloud/tail/util/util.go:22 +0xc7
github.com/hpcloud/tail/watch.(*InotifyTracker).run(0xc421c26600)
        /var/vcap/packages/blackbox/src/github.com/hpcloud/tail/watch/inotify_tracker.go:231 +0x4c8
created by github.com/hpcloud/tail/watch.glob..func1
        /var/vcap/packages/blackbox/src/github.com/hpcloud/tail/watch/inotify_tracker.go:54 +0x1dd
```

We found that this was due to a large number of files matching the tail pattern which exceeded the number of file handles available. We now have a solution for our release where we are not creating such a large number of files.

Just wanted to ask if the behaviour above is expected?

**Comment by phopper-pivotal** [comment] 2019-04-15 17:49
@carlo-colombo any workaround for this issue. just hit this with blackbox on a master PKS node

**Comment by zankich** [comment] 2019-04-15 19:03
@anEXPer can you provide any insight into this issue?

**Comment by aminjam** [comment] 2021-12-16 17:00
@carlo-colombo I would like to follow up on this issue. 

I tried reproducing this issue and I was able to get this error in my terminal when blackbox was configured to watch more than 500 files at a time and that was because I hit the open file limit maximum for my terminal. I then increased the open file limit to a very high number and was able to watch more than 1000 files. In conclusion, I don't think I expect to see this error in the cases it hasn't reached the maximum open file limit. 

I am going to close this ticket and let us know if you are still having an issue.

**Closed by aminjam** 2021-12-16 17:00 UTC
Labels: unscheduled
